# Generated by Django 6.0.7 on 2026-07-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, unique=True)),
                ('translation', models.TextField()),
                ('pronunciation', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.BigIntegerField(blank=True, db_index=True, help_text='NULL=系统词本；否则为 yusuan user_id', null=True)),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(blank=True, help_text='highschool / cet4 / cet6 / NULL(自定义)', max_length=40, null=True)),
                ('type', models.CharField(choices=[('system', '系统词本'), ('custom', '自定义词本')], default='system', max_length=10)),
                ('source', models.CharField(blank=True, help_text='内置词表来源标识，如 PEPGaoZhong', max_length=120, null=True)),
                ('created_at', models.BigIntegerField(help_text='Unix ms 时间戳')),
            ],
            options={
                'db_table': 'wordbooks',
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'name'), name='uq_owner_name')],
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('ef', models.FloatField(default=2.5, help_text='SM-2 ease factor')),
                ('interval', models.IntegerField(default=0, help_text='SM-2 间隔(天)')),
                ('repetitions', models.IntegerField(default=0)),
                ('due', models.BigIntegerField(default=0, help_text='下次复习 Unix ms')),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='vocab.word')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='vocab.wordbook')),
            ],
            options={
                'db_table': 'user_word_progress',
                'indexes': [models.Index(fields=['user_id', 'wordbook', 'due'], name='idx_progress_due')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'wordbook', 'word'), name='uq_user_wordbook_word')],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('grade', models.SmallIntegerField(help_text='SM-2 评分 0-5')),
                ('ts', models.BigIntegerField(help_text='Unix ms 时间戳')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='vocab.word')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='vocab.wordbook')),
            ],
            options={
                'db_table': 'study_logs',
                'indexes': [models.Index(fields=['user_id', 'ts'], name='idx_log_user_ts')],
            },
        ),
        migrations.CreateModel(
            name='WordbookWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordbook_links', to='vocab.word')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='vocab.wordbook')),
            ],
            options={
                'db_table': 'wordbook_words',
                'constraints': [models.UniqueConstraint(fields=('wordbook', 'word'), name='uq_wordbook_word')],
            },
        ),
    ]
