# Generated by Django 6.0.7 on 2026-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definitions',
            field=models.JSONField(blank=True, help_text='[{"pos": "n.", "definition": "..."}]', null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.JSONField(blank=True, help_text='[{"en": "...", "zh": "..."}]', null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='phrases',
            field=models.JSONField(blank=True, help_text='[{"phrase": "...", "meaning": "..."}]', null=True),
        ),
    ]
