# Generated by Django 6.0.7 on 2026-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_word_definitions_word_examples_word_phrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('daily_new_word_goal', models.IntegerField(default=20, help_text='每日新学单词数上限')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.AddField(
            model_name='studylog',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, help_text='本次是否为新学单词(用于每日新词上限统计)'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='source',
            field=models.CharField(default='study', help_text='记录来源: study(学习)/quiz(测试)/review(复习)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='studylog',
            index=models.Index(fields=['user_id', 'source'], name='idx_log_user_source'),
        ),
    ]
