# Generated by Django 6.0.7 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0004_userphraseprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="daily_quiz_goal",
            field=models.IntegerField(default=20, help_text="每日智能练习题数目标"),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_daily_plan",
            field=models.BooleanField(default=True, help_text="是否显示每日学习计划"),
        ),
    ]
