# Generated by Django 6.0.7 on 2026-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_usersettings_daily_quiz_goal_and_show_daily_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='activity_type',
            field=models.CharField(blank=True, help_text='练习题型；历史记录为空', max_length=32, null=True),
        ),
    ]
