# Generated by Django 5.2.16 on 2026-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_daily_study_consolidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='target_finish_date',
            field=models.DateField(blank=True, help_text='目标完成词本日期', null=True),
        ),
    ]
