# Generated by Django 5.2.16 on 2026-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_usersettings_target_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudysession',
            name='review_deferred',
            field=models.PositiveIntegerField(default=0, help_text='建队列时因复习上限而顺延到次日的到期复习数'),
        ),
    ]
